### ISSUE TITLE
Fix the alignment of the text-area to center 

### ISSUE THREAD

**Issue by Panth1823** [Panth1823/Textplorer-react#5]
![image](https://github.com/Panth1823/Textplorer-react/assets/89696311/7048ccc2-3f8e-4f9a-af45-8b23fd7907e8)

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign

Also, it would be great if you could elaborate a little on the expected result.

**Comment by Panth1823** [comment]
@IrfanSalim cool i would like all the div and textareas in the center and u can even add a bit of ui if you want

**Comment by IrfanSalim** [comment]
![image](https://github.com/Panth1823/Textplorer-react/assets/109443065/3450b4ea-2e5d-430a-92a1-948fc52cc163)

how does this look
