### ISSUE TITLE
Redesign favicon

### ISSUE THREAD

**Issue by Panth1823** [Panth1823/Textplorer-react#8]
Redesign the favicon it should be : 
Minimalistic
Simple
Modern

Show your creativity and feel free to ask about it 👍🏻

**Comment by Sky-De** [comment]
@Panth1823 hi, assign this to me, i will fix this for you
Thanks

**Comment by Panth1823** [comment]
@Sky-De go for it

**Comment by Sky-De** [comment]
@Panth1823 Hello, since the issue has been resolved, could you please mark it as completed and close it? Thank you.
